# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 40a16a012ee6992c3092af340d2c3b581dc9bb11c5355aaedbb0f621ca11ee0b6a7293872a1d2f6eb96e3ed3b9734178ff8f78799e74622625af2374e6226e7c

test:
  secret_key_base: 799645cf76a79d219cb06ba5f01d52fe0ab77c0f33e8a56ee5cd1ba852f6d56a3ed1f500d6a40b642bfefc0a5f3956f5f54a0d83cf8bffea25032e41053b945c

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
